import {
  Settings,
  Wrench,
  Battery,
  Car,
  Zap,
  Circle,
  Lightbulb,
  Droplets,
  Cog,
  Thermometer,
  Fuel,
  Palette,
  ToolCase,
  Rocket,
  Shield,
} from "lucide-react";

// Default category icons mapping for fallback
export const defaultCategoryIcons = {
  engine: Settings,
  brakes: Wrench,
  electrical: Battery,
  suspension: Car,
  exhaust: Zap,
  tires: Circle,
  lighting: Lightbulb,
  fluids: Droplets,
  transmission: Cog,
  cooling: Thermometer,
  fuel: Fuel,
  interior: Palette,
  tools: ToolCase,
  performance: Rocket,
  maintenance: Shield,
};

// Default category colors for fallback
export const defaultCategoryColors = {
  engine: "from-red-500 to-orange-500",
  brakes: "from-blue-500 to-cyan-500",
  electrical: "from-yellow-500 to-amber-500",
  suspension: "from-green-500 to-emerald-500",
  exhaust: "from-purple-500 to-pink-500",
  tires: "from-gray-500 to-slate-500",
  lighting: "from-indigo-500 to-blue-500",
  fluids: "from-orange-500 to-red-500",
  transmission: "from-teal-500 to-cyan-500",
  cooling: "from-blue-500 to-indigo-500",
  fuel: "from-green-500 to-teal-500",
  interior: "from-pink-500 to-rose-500",
  tools: "from-gray-500 to-zinc-500",
  performance: "from-red-500 to-pink-500",
  maintenance: "from-emerald-500 to-green-500",
};
